# Generated by Django 6.0.6 on 2026-07-20 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_alter_incident_tipo_incidente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('INCIDENTE_CRIADO', 'Incidente criado'), ('STATUS_ALTERADO', 'Status alterado'), ('ANALISTA_ATRIBUIDO', 'Analista atribuído'), ('CRITICIDADE_ALTERADA', 'Criticidade alterada'), ('INCIDENTE_ENCERRADO', 'Incidente encerrado'), ('INCIDENTE_CANCELADO', 'Incidente cancelado')], max_length=30)),
                ('descricao', models.TextField()),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_novo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incidents.incident')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_timeline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
