# Generated by Django 6.0.6 on 2026-08-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttimeline',
            name='acao',
            field=models.CharField(choices=[('INCIDENTE_CRIADO', 'Incidente criado'), ('STATUS_ALTERADO', 'Status alterado'), ('ANALISTA_ATRIBUIDO', 'Analista atribuído'), ('COMENTARIO_ADICIONADO', 'Comentario adicionado'), ('CRITICIDADE_ALTERADA', 'Criticidade alterada'), ('INCIDENTE_ENCERRADO', 'Incidente encerrado'), ('INCIDENTE_CANCELADO', 'Incidente cancelado')], max_length=30),
        ),
    ]
