# Generated by Django 6.0.6 on 2026-07-02 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('tipo_incidente', models.CharField(choices=[('Phishing', 'Phishing'), ('Malware', 'Malware'), ('ACESSO_INDEVIDO', 'Acesso indevido'), ('VAZAMENTO_DADOS', 'Vazamento de dados'), ('FALHA_SISTEMA', 'Falha de sistema'), ('COMPORTAMENTO_SUSPEITO', 'Comportamento suspeito'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30)),
                ('criticidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='BAIXA', max_length=10)),
                ('impacto', models.PositiveSmallIntegerField()),
                ('urgencia', models.PositiveSmallIntegerField()),
                ('envolve_dados_sensiveis', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_TRIAGEM', 'Em triagem'), ('EM_INVESTIGACAO', 'Em investigação'), ('CONTIDO', 'Contido'), ('RESOLVIDO', 'Resolvido'), ('FALSO_POSITIVO', 'Falso positivo'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('observacoes_finais', models.TextField(blank=True)),
                ('analista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_assumidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
