# Generated by Django 6.0.6 on 2026-07-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='tipo_incidente',
            field=models.CharField(choices=[('PHISHING', 'Phishing'), ('MALWARE', 'Malware'), ('ACESSO_INDEVIDO', 'Acesso indevido'), ('VAZAMENTO_DADOS', 'Vazamento de dados'), ('FALHA_SISTEMA', 'Falha de sistema'), ('COMPORTAMENTO_SUSPEITO', 'Comportamento suspeito'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
    ]
